spring:
  application:
    name: springAi
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        base_url: https://generativelanguage.googleapis.com
        completions-path: /v1beta/openai/chat/completions
        options:
          model: gemini-2.0-flash
